language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "debianw@gmail.com"
  - git config --global user.name "debianw"
script:
  - npm install grunt
  - npm install grunt-cli
  - grunt travis
after_script:
  - git clone https://debianw:${GH_TOKEN}@github.com/debianw/component-foundation.git
  - cp -r dist/assets/* component-foundation/
  - cd component-foundation
  - git remote rm origin
  - git remote add origin https://mhayes:${GH_TOKEN}@github.com/debianw/component-foundation.git
  - git add .
  - git commit -m "Foundation build to component-foundation"
  - git push -fq origin master
  - echo -e "Done with magic\n"
env:
  global:
    secure: USNBfNsfQFF6UgNzXRXA+8mWc66WvOUXjIH5PRjbBRUfUFZkt0a74P7uW/IMJZ0XlQwbWCphzv6Rh1qfI5bbmh6nwlJtBgP6KCc/GrPyN61YrudmPZfiNrHFkylhELz82CE6oWZjZGRwlCsLa3IADo27azmQx7kJhko5t3war5A=
notifications:
  email:
    recipients:
      - debianw@gmail.com
